### ISSUE TITLE
Mod conflict with Origins Mod

### ISSUE THREAD

**Issue by K0-RR** [DawnTeamMC/DawnAPI#2]
MC crashes (but the game is still logging) when loading Dawn API and Origins mod.

Reported to apace100 too - https://github.com/apace100/origins-fabric/issues/45

crash report - https://hatebin.com/qnmeozqeaw
latest.log - https://hatebin.com/flwzviqyah - warning very long file

**Comment by Hugman76** [comment]
Please provide a crash report.

**Comment by K0-RR** [comment]
Crash report provided

**Comment by Zarpyk** [comment]
Same error using Dawn API v1.5.2
Crash report & Log: https://gist.github.com/GuerreroCraft61/4f046ea85b5e6c0cca95f9debb283828

**Comment by K0-RR** [comment]
Yep, still

**Comment by dranorter** [comment]
I'm experiencing this as well, so I tried recompiling without the specific mixin that's causing the problem (BackgroundRendererMixin  - so this would mess with Foresight.) Unfortunately I'm getting errors having to do with the version of Modmenu, so I haven't even got the project to build.

**Comment by crysthala** [comment]
Getting this issue as well. [crash-2020-10-31_22.22.12-client.txt](https://github.com/DawnTeamMC/DawnAPI/files/5470146/crash-2020-10-31_22.22.12-client.txt) The two ran fine together before I updated a bunch of things, so I'm going to see if I can narrow down what update did it.

ETA: Dawn API 1.5 is the culprit, which makes sense, since I see in the commits that they added some Foresight stuff.
[crash-2020-10-31_22.36.19-client.txt](https://github.com/DawnTeamMC/DawnAPI/files/5470152/crash-2020-10-31_22.36.19-client.txt).

**Comment by crysthala** [comment]
> I'm experiencing this as well, so I tried recompiling without the specific mixin that's causing the problem (BackgroundRendererMixin - so this would mess with Foresight.) Unfortunately I'm getting errors having to do with the version of Modmenu, so I haven't even got the project to build.

I went into the .jar and removed the `BackgroundRendererMixin` line, so the loader ignores that file, and the game starts up just fine. I don't trust it to _run,_ mind, because anything that relies on that mixin is going to 'splode. But it is that mixin, and only that specific one. These `@redirect` conflicts are a plague upon our lovely Fabric house. :(

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version, thanks to the mod's author, apace100.
